# Backtracking

In [7]:
import numpy as np
listed_game=[
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
]
matrix_game=np.matrix(listed_game)

In [8]:
matrix_game

matrix([[5, 3, 0, 0, 7, 0, 0, 0, 0],
        [6, 0, 0, 1, 9, 5, 0, 0, 0],
        [0, 9, 8, 0, 0, 0, 0, 6, 0],
        [8, 0, 0, 0, 6, 0, 0, 0, 3],
        [4, 0, 0, 8, 0, 3, 0, 0, 1],
        [7, 0, 0, 0, 2, 0, 0, 0, 6],
        [0, 6, 0, 0, 0, 0, 2, 8, 0],
        [0, 0, 0, 4, 1, 9, 0, 0, 5],
        [0, 0, 0, 0, 8, 0, 0, 7, 9]])

In [9]:
def check_column(num,col):
    global matrix_game
    for r in range(0,9):
        if matrix_game[r,col]==num:
            return True
    return False

def check_row(num,row):
    global matrix_game
    for c in range(0,9):
        if matrix_game[row,c]==num:
            return True
    return False

def check_box(num,row,col):
    global matrix_game
    ranges=[[0,1,2],[3,4,5],[6,7,8]]
    rows=ranges[int(row/3)]
    cols=ranges[int(col/3)]
    for r in rows:
        for c in cols:
            if matrix_game[r,c]==num:
                return True
    return False    

def possible(num,row,col):
    global matrix_game
    if  not check_column(num,col) and not check_row(num,row) and not check_box(num,row,col):
        return True
    else:
        return False


In [10]:
for i in range(1,10):
    print(possible(i,4,4),check_column(i,4),check_row(i,4),check_box(i,4,4),i)

False True True False 1
False True False True 2
False False True True 3
False False True False 4
True False False False 5
False True False True 6
False True False False 7
False True True True 8
False True False False 9


In [11]:
def solve():
    global matrix_game
    for r in range(9):
        for c in range(9):
            if matrix_game[r,c]==0:
                for n in range(1,10):
                    if possible(n,r,c): ### recurssion termination condition
                        matrix_game[r,c]=n
                        solve()   ######branching
                        matrix_game[r,c]=0 ### backtracking
            if matrix_game[r,c]==0:
                return ###matrix_game[r,c]==0 but unable to place any value between 1-9 ##deadend
    print(matrix_game)

In [12]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
